#!/usr/bin/env bash

set -euo pipefail

AWS_PROFILE_NAME=$(aws configure list-profiles | fzf)

if [[ -z "${AWS_PROFILE_NAME:-}" ]]; then
  exit 0
fi

selected=$(
  AWS_PROFILE="$AWS_PROFILE_NAME" aws ec2 describe-instances --output json |
    jq -r '
      .Reservations[].Instances[] |
      (
        if .State.Name == "running" then "🟢"
        elif .State.Name == "pending" then "🟡"
        elif .State.Name == "stopping" then "🚧"
        elif .State.Name == "stopped" then "🔴"
        elif .State.Name == "shutting-down" then "🔥"
        elif .State.Name == "terminated" then "💀"
        else "❓"
        end
      ) as $status |
      "\($status) \((.Tags[]? | select(.Key=="Name") | .Value) // "sem-nome") | \(.InstanceId)"
    ' |
    sort |
    fzf
)

if [[ -z "${selected:-}" ]]; then
  exit 0
fi

instance_name="${selected%% | *}"
instance_id="${selected##*| }"

cmd="AWS_PROFILE=$AWS_PROFILE_NAME aws ssm start-session --target $instance_id"

if [[ -n "${TMUX:-}" ]]; then
  window_name="ssm:${instance_name}"

  tmux new-window -n "$window_name" "$cmd"
else
  eval "$cmd"
fi
